laser_filter_chain:
  ros__parameters:
    filter1:
      name: angle_crop_filter
      type: LaserScanAngularBoundsFilter
      params:
        lower_angle: -1.57   # -90° (lewo)
        upper_angle: 1.57    # +90° (prawo)
